name: Unity CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Unity
      uses: game-ci/setup-unity@v2
      with:
        unityVersion: 2021.1.x  # Reemplaza con la versión de Unity que estés utilizando

    - name: Build Unity project
      run: |
        unity -quit -batchmode -projectPath ./YourUnityProjectFolder -executeMethod BuildScript.Build
      env:
        BUILD_TARGET: StandaloneLinux64  # Reemplaza con tu plataforma de destino

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: BuildArtifacts
        path: ./YourUnityProjectFolder/Builds  # Reemplaza con la ruta de tus archivos de construcción
