name: Unity CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Unity
      uses: game-ci/setup-unity@v1
      with:
        unityVersion: 2021.3.22  # Reemplaza con la versión de Unity que estés utilizando

    - name: Build Unity project
      run: |
        # Aquí colocarías los comandos específicos para construir tu proyecto de Unity
        # Ejemplo: unity -quit -batchmode -projectPath ./YourUnityProjectFolder -executeMethod BuildScript.Build
      env:
        BUILD_TARGET: StandaloneLinux64  # Reemplaza con tu plataforma de destino

    - name: Create Release and Upload Build Artifacts
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./YourUnityProjectFolder/Builds/*  # Reemplaza con la ruta de tus archivos de construcción
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Get Release URL
      run: echo "Release URL: ${{ steps.create_release.outputs.upload_url }}"
