name: Unity CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Unity
      uses: game-ci/setup-unity@v1
      with:
        unityVersion: 2021.3.22  # Reemplaza con la versión de Unity que estás utilizando

    - name: Build Unity project
      run: |
        # Reemplaza con los comandos de construcción específicos de tu proyecto de Unity
        # Por ejemplo, puedes usar la CLI de Unity para construir tu proyecto:
        # Unity -quit -batchmode -projectPath ./YourUnityProjectFolder -executeMethod BuildScript.Build
      env:
        BUILD_TARGET: StandaloneWindows64  # Reemplaza con tu plataforma de destino (ejemplo: StandaloneWindows64)
